[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyBO"
version = "0.3.0"
description = "A Python library for Multi-Objective Bayesian Optimization"
readme = "readme.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Davide Beretta", email = "mail.davide.beretta@gmail.com" }
]
dependencies = [
    "numpy >= 1.25",
    "botorch == 0.13.0",
    "matplotlib >= 3.10.0",
    "scipy >= 1.15.0",
    "scikit-optimize >= 0.10.0",
    "scikit-learn >= 1.6.0",
    "gpytorch == 1.14",
    "torch == 2.8.0",
    "sympy == 1.14.0",
    "pandas~=2.3.3"
]

[tool.setuptools]
packages = ["acqf", "constraints", "objectives", "optimizer", "plotters", "samplers", "utils"]
